# -*- coding: utf-8 -*-
"""IE313-b07-l06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evOaIIIJgVc8yP7lXEzRmQdZgkfc_tZR

- MSSV: 25410291
- Họ Tên: Đinh Xuân Sâm
- GDrive: [IE313 > notebooks](https://drive.google.com/drive/folders/1nap2ahjmAj6aj1cm6xr5nZDrBFeBjc00)
- Github: [sam-uit/IE313](https://github.com/sam-uit/IE313)

# Buổi 07 - Bài 06 - Phát Triển Mô Hình

Mục tiêu:

- Vận dụng hồi quy tuyế tính đơn và đa biến.
- Biết đánh giá mô hình dùng trực quan.
- Vận dùng hồi quy đa thức và kỹ thuật Pipeline.
- Áp dụng thang đo *R-squared* và *MSE* dùng để đánh giá tập mẫu.

Nội Dung:

1. Phát triển mô hình.
2. Hồi quy tuyến tính đơn biến.
3. Hồi quy tuyến tính đa biến.
4. Đánh giá mô hình dùng trực quan.
5. Hồi quy đa thức.
6. Kỹ thuật Pipeline.
7. Thang đo *MSE* và *R-squared* ($R^2$ -- $R^2$).
8. Đánh giá.

Tóm tắt:

- Đặt vấn đề (Bài 1):
    - *Chúng ta nên bán xe đã qua sử dụng với giá bao nhiêu?*
- Hướng giải quyết (Bài 2):
    - *Tiền xử lý dữ liệu liên quan để phục vụ phân tích.*
- Phân tích thăm dò (Bài 5):
    - *Những đặc điểm nào có ảnh hưởngg nhất đến giá xe?*
- Phát triển mô hình để dự đoán (Bài 6):
    - *Cúng ta đã **xác định giá hợp lý** cho xe đã qua sử dụng như thế nào?*

## 0. Load Dataset

### Import libraries
"""

# import numpy & panda
import numpy as np
import pandas as pd

# import matplotlib
import matplotlib.pyplot as plt

# import seaborn
import seaborn as sns

"""### Data file"""

dataset_theory_url = "https://raw.githubusercontent.com/datasethub/ds105/master/Model_Dataset.csv"
dataset_theory_file = "Model_Dataset.csv"
dataset_lab_url ="https://raw.githubusercontent.com/datasethub/ds105/master/Model_Dataset_Lab.csv"
dataset_lab_file = "Model_Dataset_Lab.csv"

# download the dataset file
import requests

try:
    dataset_theory_response = requests.get(dataset_theory_url)

    with open(dataset_theory_file, "wb") as file:
        file.write(dataset_theory_response.content)

    dataset_lab_response = requests.get(dataset_lab_url)
    with open(dataset_lab_file, "wb") as file_lab:
        file_lab.write(dataset_lab_response.content)

    print("Download complete!")
except:
    print("Download failed!")

"""### `read_csv`"""

# read from a local file
df_theory = pd.read_csv(dataset_theory_file)

df_theory

"""## Xây Dựng Mô Hình

## Hồi Quy Tuyến Tính Đơn Biến

### Mô Hình

- $x$: biến độc lập (**predictor**)
- $y$: biến phụ thuộc (**target**)

$$y = b_0 + b_{1}x$$

- $b_0$: **intercept**
- $b_1$: **slope**

### Dự Đoán

### Xây Dựng (fit)

- Là 1 đường thẳng, cố gắng làm hài lòng tất cả các điểm phổ biến.
"""

# import bảo bối
from sklearn.linear_model import LinearRegression
m1 = LinearRegression()

# lấy ra các biến
X1 = df_theory[['highway-mpg']]
y = df_theory['price']

# xây dựng mô hình
m1.fit(X1, y)

b0 = m1.intercept_
b1 = m1.coef_
print(f'b0 = {b0}, b1 = {b1}')

x = 20
y = b0 + b1 * x
y

# dự đoán
m1.predict([[20]])

# dự doán, tham số là np.array
m1.predict(np.array([[20]]))

# dự doán, tham số là np.array
m1.predict(np.array([[20], [15]]))

# dự đoán
yhat = m1.predict(X1)

"""## Hồi Quy Tuyến Tính Đa Biến

$$Y = b_0 + b_{1}x_{1} + b_{2}x_{2} + b_{3}x_{3} + \ldots$$

- $b_0$: intercept (X = 0)
- $b_1$: coefficient hoặc parameter của $x_1$
- $b_2$: ... của $x_2$

### Xây Dựng
"""

# chọn biến
X2 = df_theory[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']]
y = df_theory['price']

# khai báo mô hình
m2 = LinearRegression()

# fit
m2.fit(X2, y)

b0 = m2.intercept_
b0

m2.coef_

m2.predict([[111, 2548, 130, 27]])

m2.predict([[154, 2823, 152, 26]])

df_theory[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg', 'price']]

# dự đoán
yhat = m2.predict(X2)

"""## Đánh Giá Mô Hình Trực Quan

Các mô hình:

- Regression plot
- Residual plot
- Distribution plot

### Distribution plot
"""

# distribution plot
y

# distribution plot cho y thực tế
ax1 = sns.displot(
    y,
    kind='kde',
    color='blue'
)

# distribution plot cho y dự đoán
ax2 = sns.displot(
    yhat,
    kind='kde',
    color='red'
)

# Đối chiếu 2 chuỗi giá trị
ax1 = sns.kdeplot(data=df_theory, x='price', color="blue")
sns.kdeplot(yhat, color='red', ax=ax1)

"""### Nhận Xét Mô Hình

- Mô hình có sự sai khác ở các loại xe có `price` lớn (~10000 - 40000).

### Bài Tập

- p52

## Hồi Quy Đa Thức

Polynomial regression

- Mộ trường hợp đặc biệt của mô hình hồi quy tuyến tính tổng quát.
- Mối quan hệ cong phi tuyến (curvilinear)
- Đường cong: cố gắng hài lòng tất cả các điểm (tham gia vào công thức/mô hình).

Quan hệ cong phi tuyến:

- Bình phương.
- Thiết lập các bậc cao hơn cho biến độc lập.

### Cong Phi Tuyến

### Mô Hình Đơn Biến

### Mô Hình Đa Biến

$$yHat = b_0 + b_{1}X_{1} + b_{2}X_2 + b_{3}X_{1}X_{2} + b_{4}(X_1)^2 + b_{5}(X_2)^2 + \ldots$$

$$yHat = b_0 + b_{1}a + b_{2}b + b_{3}c + b_{4}d + b_{5}e + \ldots$$

Các bước:

1. Biến đổi (transform) các biến (feature)
2. Dùng Linear Regression để xây dựng (fit)

#### B1. Biến Đổi Biến

Biến đổi các biến đa thức thành/về biến bậc 1.
"""

X3 = df_theory[['horsepower', 'curb-weight']]
y = df_theory['price']

# import PolynomialFeatures
from sklearn.preprocessing import PolynomialFeatures

# khai báo biến bậc 2
pf3 = PolynomialFeatures(degree=2, include_bias=False)

# biến đổi thử
pf3.fit_transform([[1, 2]])

# biến đổi X3
X3_pf = pf3.fit_transform(X3)
X3_pf

print("Thực tế: ", X3.shape)
print("Biến đổi: ", X3_pf.shape)

"""#### B2. Xây Dựng Mô Hình"""

# khai báo
m3 = LinearRegression()

# fit
m3.fit(X3_pf, y)

"""#### Dự Đoán"""

# dự đoán
yhat = m3.predict(X3_pf)

"""#### Đánh Giá Mô Hình Trực Quan"""

# trực quan
ax1 = sns.displot(
    y,
    kind='kde',
    color='blue'
)

# distribution plot cho y dự đoán
ax2 = sns.displot(
    yhat,
    kind='kde',
    color='red'
)

# đối chiếu
ax1 = sns.kdeplot(y, color="blue")
sns.kdeplot(yhat, color='red', ax=ax1)

"""#### Nhận Xét

- Với bậc 2, chúng ta có kết quả dự đoán sát với thực tế hơn mô hình dự đoán tuyến tính đơn biến.

#### Nhiều Bậc Hơn (Bậc 4)
"""

# features
X4 = df_theory[['horsepower', 'curb-weight']]
y = df_theory['price']

# khai báo biến đổi
pf4 = PolynomialFeatures(degree=4, include_bias=False)
X4_pf = pf4.fit_transform(X4)

# shape
print("Thực tế: ", X4.shape)
print("Biến đổi: ", X4_pf.shape)

# khai báo mô hình
m4 = LinearRegression()
# xây dựng mô hình
m4.fit(X4_pf, y)

# dự đoán
y4hat = m4.predict(X4_pf)

# đánh giá trực quan
ax1 = sns.kdeplot(
    y,
    color='blue'
)
sns.kdeplot(y4hat, color='red', ax=ax1)

"""### Quy Trình 3 Bước

1. Chuẩn hóa (Normalize)
2. Biến đổi (Transform)
3. Xây dựng (Fit)

#### Thực Hiện
"""

X5 = df_theory[['horsepower', 'curb-weight']]
y = df_theory['price']

## Bước 1. Chuẩn hóa
from sklearn.preprocessing import StandardScaler
ss5 = StandardScaler()
X5_ss = ss5.fit_transform(X5)

## Bước 2. Biến đổi
pf5 = PolynomialFeatures(degree=2, include_bias=False)
X5_pf = pf5.fit_transform(X5_ss)

print("Thực tế: ", X5.shape)
print("Biến đổi: ", X5_pf.shape)

## Bước 3. Xây dựng
m5 = LinearRegression()
m5.fit(X5_pf, y)

# dự đoán
y5hat = m5.predict(X5_pf)

# trực quan và đánh giá
ax1 = sns.kdeplot(
    y,
    color='blue'
)
sns.kdeplot(
    y5hat,
    color='red',
    ax=ax1
)

"""#### Nhận Xét

Kết quả trực quan cho thấy kết quả sai khác chút ít với mô hình m4 đã dựng "thủ công" ở trên.

- Kết quả tốt hơn ở ngưỡng < 20000
- Có sự sai lệch nhiều hơn từ 20000 - 45000

## Pipeline

- (Bán) tự động hóa Quy Trình 3 Bước ở trên.
"""

# import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# pipeline constructor
pl_inputs = [('chuanhoa', StandardScaler()),
             ('hoiquy', PolynomialFeatures(degree=2, include_bias=False)),
             ('dudoan', LinearRegression())
]

# khai bao đối tượng
pl1 = Pipeline(pl_inputs)

# xây dựng
pl1.fit(X4, y)

# dự đoán với giá trị thực tế
pl1.predict([[111, 2548]])

# dự đoán
yplhat = pl1.predict(X4)

# đối chiếu trực quan
ax1 = sns.kdeplot(y, color='blue')
sns.kdeplot(yplhat, color='red', ax=ax1)

"""### Nhận Xét

Kết quả trực quan cho thấy:

- Tương đồng hoàn toàn với kết quả của Quy Trình 3 Bước đã thực hiện thủ công trước đó.

## Bài Tập Áp Dụng

- p72
- Xây dựng mô hình hồi quy đa thức cho 4 biến bậc 3.
"""